# Generated by Django 4.2.5 on 2023-10-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_simpleuserprofile_city'),
        ('api', '0003_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Описание заявки')),
                ('location', models.CharField(max_length=255, verbose_name='Город')),
                ('price', models.CharField(default='Договорная', max_length=255, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('photo', models.ImageField(upload_to='requests/photos/', verbose_name='Фото')),
                ('hashtags', models.TextField(verbose_name='Хештег')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to='accounts.simpleuserprofile', verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_requests', to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
