# Generated by Django 4.2.5 on 2023-10-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.FileField(
                null=True, upload_to="categories/icons/", verbose_name="Иконка"
            ),
        ),
    ]
