# Generated by Django 4.2.5 on 2023-10-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                default="",
                null=True,
                upload_to="categories/icons/",
                verbose_name="Иконка",
            ),
        ),
    ]
