# Generated by Django 4.2.5 on 2023-10-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                default="",
                upload_to="categories/icons/",
                verbose_name="Иконка",
            ),
        ),
    ]
