# Generated by Django 4.2.5 on 2023-10-21 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_category_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryHashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=255, verbose_name="Название тега")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hashtags",
                        to="api.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Хештег",
                "verbose_name_plural": "Хештеги",
            },
        ),
        migrations.DeleteModel(
            name="Subcategory",
        ),
    ]
