# Generated by Django 4.2.5 on 2023-10-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_categoryhashtag_delete_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='stories/previews/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stories/photos/', verbose_name='Фото')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.story', verbose_name='История')),
            ],
        ),
    ]
