# Generated by Django 4.2.5 on 2023-10-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_story_storyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrequest",
            name="title",
            field=models.CharField(
                default="", max_length=155, verbose_name="Заголовок статьи"
            ),
        ),
    ]
