# Generated by Django 4.2.5 on 2023-11-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userrequest_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='price',
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Локация'),
        ),
    ]
