# Generated by Django 4.2.5 on 2024-01-09 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_userrequest_author_alter_userrequest_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='request/photos/', verbose_name='Фото')),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userrequest')),
            ],
        ),
    ]
