# Generated by Django 4.2.5 on 2023-10-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='tg_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
