# Generated by Django 4.2.5 on 2023-10-10 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_city_options'),
        ('accounts', '0004_alter_simpleuserprofile_city_delete_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='api.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='tg_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Айди пользователя в телеграмме'),
        ),
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='tg_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Юзер в телеграмме'),
        ),
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения'),
        ),
    ]
