# Generated by Django 4.2.5 on 2023-10-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_simpleuserprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuserprofile',
            name='is_banned',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Блокировка'),
        ),
    ]
