# Generated by Django 4.2.5 on 2023-10-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_simpleuserprofile_is_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
    ]
