# Generated by Django 4.2.5 on 2023-11-21 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_serviceuserrequestresponse'),
        ('accounts', '0007_alter_simpleuserprofile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_series', models.CharField(max_length=5, verbose_name='Серия паспорта')),
                ('passport_number', models.IntegerField(verbose_name='Номер паспорта')),
                ('hashtags', models.TextField(verbose_name='Хештег')),
                ('info_about', models.TextField(verbose_name='О себе')),
                ('education', models.TextField(verbose_name='Образование')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.category', verbose_name='Категория')),
                ('service_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.simpleuserprofile', verbose_name='Сервис')),
            ],
            options={
                'verbose_name': 'Настройка сервиса',
                'verbose_name_plural': 'Настройки сервиса',
            },
        ),
    ]
