# Generated by Django 4.2.5 on 2023-11-21 20:12

import accounts.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_servicesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesetting',
            name='service_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.simpleuserprofile', validators=[accounts.validators.validate_is_profile_servie], verbose_name='Сервис'),
        ),
    ]
