# Generated by Django 4.2.5 on 2023-11-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_serviceuserrequestresponse'),
        ('accounts', '0009_alter_servicesetting_service_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesetting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='servicesetting',
            name='education',
            field=models.TextField(blank=True, default='', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='servicesetting',
            name='info_about',
            field=models.TextField(blank=True, default='', verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='servicesetting',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='servicesetting',
            name='passport_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='servicesetting',
            name='passport_series',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Серия паспорта'),
        ),
    ]
