# Generated by Django 4.2.5 on 2023-11-21 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_servicesetting_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesetting',
            name='service_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.simpleuserprofile', verbose_name='Сервис'),
        ),
    ]
