# Generated by Django 4.2.5 on 2023-11-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_servicesetting_service_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesetting',
            name='address_by_location',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес'),
        ),
    ]
