# Generated by Django 4.2.5 on 2023-11-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_servicesetting_address_by_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesetting',
            name='hashtags',
            field=models.TextField(blank=True, default='', verbose_name='Хештег'),
        ),
    ]
