# Generated by Django 4.2.5 on 2024-01-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_servicesetting_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesetting',
            name='address_by_location',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='servicesetting',
            name='education',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='servicesetting',
            name='hashtags',
            field=models.TextField(verbose_name='Хештег'),
        ),
        migrations.AlterField(
            model_name='servicesetting',
            name='info_about',
            field=models.TextField(blank=True, default='', null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='servicesetting',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='servicesetting',
            name='passport_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='servicesetting',
            name='passport_series',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Серия паспорта'),
        ),
    ]
